import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
[font]
size = 8
offset = { x = 0, y = 0}
# draw_bold_text_with_bright_colors = false
[font.normal]
family = "JetbrainsMono Nerd Font"
style = "SemiBold"
[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"
[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"
[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"
[window]
padding = {x = 0, y = 0}
dynamic_padding = true
# opacity = 0.9
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
